### ISSUE TITLE
VPS tutorial (IP to Domain)

### ISSUE THREAD

**Issue by master3395** [greatplainsmodding/DBM-Dashboard#1]
Hello, perhaps a tutorial for how to set it up on a VPS could help.
I saw the windows tutorial, and i liked it.
Sadly my VPS is using Linux or ubuntu.
And the tutorial for windows doesn't cover it :/

**Comment by greatplainsmodding** [comment]
Thanks for the suggestion. I will definitely will do that. You can set it up like you would on windows, make sure all your settings are configured and modules installed. You then can use something like Nginx to reverse proxy it to your domain. If you need more help you can contact me in Discord.
