### ISSUE TITLE
Glitch

### ISSUE THREAD

**Issue by LGN-Silv** [greatplainsmodding/DBM-Dashboard#10]
How to host this on glitch?

**Comment by LGN-Silv** [comment]
Check the dashboard on this repo.

**Comment by LGN-Silv** [comment]
https://github.com/DetroitWhiskey136/project-redwing

**Comment by greatplainsmodding** [comment]
@LGN-Silv what?

**Comment by LGN-Silv** [comment]
Check the dashboard he made on his DBM bot.Just see as reference https://github.com/DetroitWhiskey136/project-redwing

**Comment by LGN-Silv** [comment]
Also this extension https://github.com/greatplainsmodding/extensions/blob/master/extensions/glitch_stay_alive/dbm_glitch_EXT.js. Just paste it into extensions? Nothing else to do?

**Comment by greatplainsmodding** [comment]
That dashboard isn't made for DBM. And for that extension just place it in your bot's extension folder. You will then need to go to uptime robot and have it ping your glitch  url.

**Comment by LGN-Silv** [comment]
Okay. Thanks for making these awesome stuff <3

**Comment by greatplainsmodding** [comment]
👍

**Comment by DetroitWhiskey136** [comment]
The "dashboard" on my repo was created by the AIG folks with a couple tweaks tbh that one is so old it probably shouldn't be used, at this time i have no plans to update it to my latest one but maybe once i'm happy with it.
