### ISSUE TITLE
Followed the video instructions for glitch hosting, still stuck on "Starting"

### ISSUE THREAD

**Issue by TCMine** [greatplainsmodding/DBM-Dashboard#2]
Updated config, added callback URL, still nothing. I think these logs may have something to do with it http://prntscr.com/rb916t

**Comment by greatplainsmodding** [comment]
Make sure you pasted the following in your bots package.json file:
<code>
    "body-parser": "^1.19.0",
    "chalk": "^3.0.0",
    "figlet": "^1.2.4",
    "cookie-parser": "^1.4.4",
    "ejs": "^3.0.1",
    "express": "^4.17.1",
    "express-session": "^1.17.0",
    "fs": "0.0.1-security",
    "passport": "^0.4.1",
    "passport-discord": "^0.1.3",
    "path": "^0.12.7"
<\code>
