### ISSUE TITLE
Issue with the web panel

### ISSUE THREAD

**Issue by Ryckie** [greatplainsmodding/DBM-Dashboard#20]
When using the admin panel --> web panel page.
And saving the new text. Then going back to the web panel page, the text box of section 4 (not the title but the text bellow) and the footer is not as what it was set to. So if you would not change anything and save it again, it will change it because somehow it fills in some other text.

Example: I set every title to the title, and the text bellow to the title + the word "text"
Then when you save it it shows you that page, and shows up correctly (http://prntscr.com/soxulj)
But when you then click back on admin panel > web panel. The text gets changed and if you then press save it looks like this: (http://prntscr.com/soxwwb)

**Comment by greatplainsmodding** [comment]
fixed ;)
