### ISSUE TITLE
Website SSL?

### ISSUE THREAD

**Issue by ArtieFuzz** [greatplainsmodding/DBM-Dashboard#7]
This isn't an issue but is it possible to make the website secure? 
Examples: https://glitch.com/edit/#!/force-http-or-https?path=server.js:1:0 (Code)
https://force-http-or-https.glitch.me/ (Website)

**Comment by greatplainsmodding** [comment]
Use something like a cert bot.

**Comment by ArtieFuzz** [comment]
but glitch already has a SSL certificate

**Comment by ArtieFuzz** [comment]
you just have to redirect it

**Comment by ArtieFuzz** [comment]
Also i can’t use cert bot
